name: reinforce
channels:
  - conda-forge
dependencies:
  - gymnasium
  - gymnasium-box2d
  - ipykernel
  - jupyterlab
  - python=3.11
  - stable-baselines3
  - pettingzoo
  - cmake
  - tensorboard
  - pip:
    - supersuit
    - generals-bots
    - ray[rllib]
    - open_spiel
